services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-13.22-alpine3.22}
    container_name: ${POSTGRES_CONTAINER_NAME:-postgres_db}
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mydatabase}
      POSTGRES_USER: ${POSTGRES_USER:-myuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - postgres_network
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4:${PGADMIN_VERSION:-latest}
    container_name: ${PGADMIN_CONTAINER_NAME:-pgadmin}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - postgres_network
    env_file:
      - .env

volumes:
  postgres_data:
    name: ${POSTGRES_VOLUME_NAME:-postgres_data}
    driver: local
  pgadmin_data:
    name: ${PGADMIN_VOLUME_NAME:-pgadmin_data}
    driver: local

networks:
  postgres_network:
    name: postgres_network
    driver: bridge